name: Test & deploy

on:
  push:
    branches: [ master ]
    tags:
      - '**'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Cache
      uses: actions/cache@v2.1.6
      with:
        path: /home/runner/.m2/repository
        key: ${{ runner.os }}-${{ hashFiles('pom.xml') }}
        
    - name: Build with Maven
      run: mvn -B test --file pom.xml

  github-release:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Cache
      uses: actions/cache@v2.1.6
      with:
        path: /home/runner/.m2/repository
        key: ${{ runner.os }}-${{ hashFiles('pom.xml') }}
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests=true
    
    - name: Create release archive
      run: |
        mkdir packager-tmp && cp -r resources/* ./packager-tmp && cp target/*.jar ./packager-tmp
        cd ./packager-tmp && tar -czvf joal.tar.gz * && mv ./joal.tar.gz ../ && cd ..

    
    - name: Create Github release
    
      uses: ncipollo/release-action@v1.8.6
      with:
        allowUpdates: true
        artifactErrorsFailBuild: true
        artifacts: "joal.tar.gz"
        draft: true
        tag: a
        token: ${{ secrets.GITHUB_TOKEN }}

